add missing header for gcc15
fix:
```cpp
[ 57%] Building CXX object CMakeFiles/ffw_robot_manager.dir/src/battery_model.cpp.o
In file included from /build/ai_worker-release-release-jazzy-ffw_robot_manager-1.1.20-1/src/battery_model.cpp:17:
/build/ai_worker-release-release-jazzy-ffw_robot_manager-1.1.20-1/include/ffw_robot_manager/battery_model.hpp:68:11: error: 'uint8_t' does not name a type
   68 |   virtual uint8_t get_power_supply_technology() const = 0;
      |           ^~~~~~~
```